<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Kerjasama;

class KerjasamaSeeders extends Seeder
{
    public function run()
    {
        $data = [
            [
                'mitra' => 'Mitra A',
                'kerjasama' => 'Kerjasama A',
                'tanggal_mulai' => '2023-01-01',
                'tanggal_selesai' => '2024-01-01',
                'nomor' => 'KS-001',
                'kegiatan' => 'Kegiatan A',
                'sifat' => 'Lokal',
                'kriteria_kemitraan_id' => '1, 2, 3',
                'kriteria_mitra_id' => 1,
                'bidang_kerjasama_id' => 1,
                'pks' => rand(1, 3),
                'jurusan' => rand(1,15),
                'prodi' => rand(1,44),
                'pic_pnj' => 'Muhammad Husain Al Ghazali',
                'alamat_perusahaan' => 'Jl. Perusahaan A, City A',
                'pic_industri' => 'PIC Industri A',
                'jabatan_pic_industri' => 'Manager',
                'telp_industri' => '081212345678',
                'email' => 'mitraA@example.com',
                'file' => 'file_A.pdf',
                'step' => 1,

                'reviewer_id' => 1,
                'target_reviewer_id' => 2,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mitra' => 'Mitra B',
                'kerjasama' => 'Kerjasama B',
                'tanggal_mulai' => '2023-02-01',
                'tanggal_selesai' => '2024-02-01',
                'nomor' => 'KS-002',
                'kegiatan' => 'Kegiatan B',
                'sifat' => 'Nasional',
                'kriteria_kemitraan_id' => '4, 5, 6',
                'kriteria_mitra_id' => 2,
                'bidang_kerjasama_id' => 2,
                'pks' => rand(1, 3),
                'jurusan' => rand(1,15),
                'prodi' => rand(1,44),
                'pic_pnj' => 'Muhammad Husain Al Ghazali',
                'alamat_perusahaan' => 'Jl. Perusahaan B, City B',
                'pic_industri' => 'PIC Industri B',
                'jabatan_pic_industri' => 'Supervisor',
                'telp_industri' => '081298765432',
                'email' => 'mitraB@example.com',
                'file' => 'file_B.pdf',
                'step' => 2,

                'reviewer_id' => 2,
                'target_reviewer_id' => 3,
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mitra' => 'Mitra C',
                'kerjasama' => 'Kerjasama C',
                'tanggal_mulai' => '2023-03-01',
                'tanggal_selesai' => '2024-03-01',
                'nomor' => 'KS-003',
                'kegiatan' => 'Kegiatan C',
                'sifat' => 'Internasional',
                'kriteria_kemitraan_id' => '7, 8, 9',
                'kriteria_mitra_id' => 3,
                'bidang_kerjasama_id' => 3,
                'pks' => rand(1, 3),
                'jurusan' => rand(1,15),
                'prodi' => rand(1,44),
                'pic_pnj' => 'Muhammad Husain Al Ghazali',
                'alamat_perusahaan' => 'Jl. Perusahaan C, City C',
                'pic_industri' => 'PIC Industri C',
                'jabatan_pic_industri' => 'Staff',
                'telp_industri' => '081234567890',
                'email' => 'mitraC@example.com',
                'file' => 'file_C.pdf',
                'step' => 3,

                'reviewer_id' => 3,
                'target_reviewer_id' => 4,
                'user_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mitra' => 'Mitra D',
                'kerjasama' => 'Kerjasama D',
                'tanggal_mulai' => '2023-04-01',
                'tanggal_selesai' => '2024-04-01',
                'nomor' => 'KS-004',
                'kegiatan' => 'Kegiatan D',
                'sifat' => 'Lokal',
                'kriteria_kemitraan_id' => '1, 2, 4',
                'kriteria_mitra_id' => 4,
                'bidang_kerjasama_id' => 4,
                'pks' => rand(1, 3),
                'jurusan' => rand(1,15),
                'prodi' => rand(1,44),
                'pic_pnj' => 'Muhammad Husain Al Ghazali',
                'alamat_perusahaan' => 'Jl. Perusahaan D, City D',
                'pic_industri' => 'PIC Industri D',
                'jabatan_pic_industri' => 'Engineer',
                'telp_industri' => '081345678901',
                'email' => 'mitraD@example.com',
                'file' => 'file_D.pdf',
                'step' => 4,

                'reviewer_id' => 4,
                'target_reviewer_id' => 5,
                'user_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mitra' => 'Mitra E',
                'kerjasama' => 'Kerjasama E',
                'tanggal_mulai' => '2023-05-01',
                'tanggal_selesai' => '2024-05-01',
                'nomor' => 'KS-005',
                'kegiatan' => 'Kegiatan E',
                'sifat' => 'Nasional',
                'kriteria_kemitraan_id' => '5, 6, 7',
                'kriteria_mitra_id' => 5,
                'bidang_kerjasama_id' => 5,
                'pks' => rand(1, 3),
                'jurusan' => rand(1,15),
                'prodi' => rand(1,44),
                'pic_pnj' => 'Muhammad Husain Al Ghazali',
                'alamat_perusahaan' => 'Jl. Perusahaan E, City E',
                'pic_industri' => 'PIC Industri E',
                'jabatan_pic_industri' => 'Consultant',
                'telp_industri' => '081456789012',
                'email' => 'mitraE@example.com',
                'file' => 'file_E.pdf',
                'step' => 5,

                'reviewer_id' => 5,
                'target_reviewer_id' => 6,
                'user_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mitra' => 'Mitra F',
                'kerjasama' => 'Kerjasama F',
                'tanggal_mulai' => '2023-06-01',
                'tanggal_selesai' => '2024-06-01',
                'nomor' => 'KS-006',
                'kegiatan' => 'Kegiatan F',
                'sifat' => 'Internasional',
                'kriteria_kemitraan_id' => '8, 9, 10',
                'kriteria_mitra_id' => 6,
                'bidang_kerjasama_id' => 6,
                'pks' => rand(1, 3),
                'jurusan' => rand(1,15),
                'prodi' => rand(1,44),
                'pic_pnj' => 'Muhammad Husain Al Ghazali',
                'alamat_perusahaan' => 'Jl. Perusahaan F, City F',
                'pic_industri' => 'PIC Industri F',
                'jabatan_pic_industri' => 'Director',
                'telp_industri' => '081567890123',
                'email' => 'mitraF@example.com',
                'file' => 'file_F.pdf',
                'step' => 6,

                'reviewer_id' => 6,
                'target_reviewer_id' => 7,
                'user_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mitra' => 'Mitra G',
                'kerjasama' => 'Kerjasama G',
                'tanggal_mulai' => '2023-07-01',
                'tanggal_selesai' => '2024-07-01',
                'nomor' => 'KS-007',
                'kegiatan' => 'Kegiatan G',
                'sifat' => 'Lokal',
                'kriteria_kemitraan_id' => '1, 3, 5',
                'kriteria_mitra_id' => 7,
                'bidang_kerjasama_id' => 6,
                'pks' => rand(1, 3),
                'jurusan' => rand(1,15),
                'prodi' => rand(1,44),
                'pic_pnj' => 'Muhammad Husain Al Ghazali',
                'alamat_perusahaan' => 'Jl. Perusahaan G, City G',
                'pic_industri' => 'PIC Industri G',
                'jabatan_pic_industri' => 'CEO',
                'telp_industri' => '081678901234',
                'email' => 'mitraG@example.com',
                'file' => 'file_G.pdf',
                'step' => 7,

                'reviewer_id' => 7,
                'target_reviewer_id' => 8,
                'user_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($data as $item) {
            Kerjasama::create($item);
        }
    }
}
